
CREATE TABLE MEMBER_T(
    MEM_NO          NUMBER(1)           NOT NULL,
    MEM_ID          VARCHAR2(30 BYTE)   NOT NULL    UNIQUE,
    MEM_PW          VARCHAR2(30 BYTE)   NOT NULL,
    MEM_POINT       NUMBER              NULL,
    MEM_GUBUN       VARCHAR2(7 BYTE)    NOT NULL    CHECK(MEM_GUBUN IN('REGULAR', 'SOCIAL')),
    MEM_EMAIL       VARCHAR2(100 BYTE)  NULL        UNIQUE
);

ALTER TABLE MEMBER_T ADD ADRESS     VARCHAR2(200 BYTE) NULL;
ALTER TABLE MEMBER_T ADD JOINED_DT  DATE               NULL;

COMMIT;

ALTER TABLE MEMBER_T DROP COLUMN JOINED_DT;

COMMIT;

ALTER TABLE MEMBER_T RENAME COLUMN MEM_PW TO MEM_PWD;

COMMIT;

ALTER TABLE MEMBER_T ADD CONSTRAINT PK_MEMBER PRIMARY KEY(MEM_NO);

COMMIT;



CREATE TABLE BOARD_T(
    BOARD_NO            NUMBER              NOT NULL,
    TITLE               VARCHAR2(4000 BYTE) NOT NULL,
    CONTENT             CLOB                NOT NULL,
    HIT                 VARCHAR2(1 BYTE)    NOT NULL,
    MEM_ID              VARCHAR2(30 BYTE)   NOT NULL,
    CREATED_DT          DATE
);

ALTER TABLE BOARD_T  MODIFY HIT NUMBER NOT NULL;

COMMIT;

ALTER TABLE BOARD_T  ADD CONSTRAINT PK_BOARD PRIMARY KEY(BOARD_NO);

COMMIT;
 
ALTER TABLE BOARD_T ADD CONSTRAINT FK_MEMBER_BOARD FOREIGN KEY(MEM_ID) REFERENCES MEMBER_T(MEM_ID) ON DELETE CASCADE;

COMMIT;

DROP TABLE BOARD_T;
DROP TABLE MEMBER_T;