DROP TABLE EMPLOYEE_TBL;
DROP TABLE DEPARTMENT_TBL;

CREATE TABLE DEPARTMENT_TBL(
    DEPT_NO             NUMBER(1)           NOT NULL,
    DEPT_NAME           VARCHAR2(15 BYTE)   NOT NULL,
    LOCATION            VARCHAR2(15 BYTE)   NOT NULL,
    CONSTRAINT DPT_PK PRIMARY KEY(DEPT_NO)
);
CREATE TABLE EMPLOYEE_TBL(
    EMP_NO              NUMBER(4)           NOT NULL,
    NAME                VARCHAR2(20 BYTE)   NOT NULL,
    DEPART              NUMBER(1)           NULL,
    POSITION            VARCHAR2(20 BYTE)   NULL,
    GENDER              CHAR    (2 BYTE)    NULL,
    HIRE_DATE           DATE                NULL,
    SALARY              NUMBER              NULL,
    CONSTRAINT EMP_PK       PRIMARY KEY(EMP_NO),
    CONSTRAINT DPT_EMP_FK   FOREIGN KEY(DEPART)   REFERENCES DEPARTMENT_TBL(DEPT_NO)
    ON DELETE CASCADE
);

DROP SEQUENCE DPT_SEQ;
CREATE SEQUENCE DPT_SEQ NOORDER;

INSERT INTO DEPARTMENT_TBL(DEPT_NO,DEPT_NAME, LOCATION) VALUES(DPT_SEQ.NEXTVAL, '영업부', '대구');
INSERT INTO DEPARTMENT_TBL(DEPT_NO,DEPT_NAME, LOCATION) VALUES(DPT_SEQ.NEXTVAL, '인사부', '서울');
INSERT INTO DEPARTMENT_TBL(DEPT_NO,DEPT_NAME, LOCATION) VALUES(DPT_SEQ.NEXTVAL, '총무부', '대구');
INSERT INTO DEPARTMENT_TBL(DEPT_NO,DEPT_NAME, LOCATION) VALUES(DPT_SEQ.NEXTVAL, '기획부', '서울');

DROP SEQUENCE EMP_SEQ;
CREATE SEQUENCE EMP_SEQ 
START WITH 1001
NOORDER;

INSERT INTO EMPLOYEE_TBL(EMP_NO,NAME, DEPART, POSITION, GENDER, HIRE_DATE, SALARY) VALUES(EMP_SEQ.NEXTVAL, '구창민', 1, '과장', 'M', '95-05-01', 5000000);
INSERT INTO EMPLOYEE_TBL(EMP_NO,NAME, DEPART, POSITION, GENDER, HIRE_DATE, SALARY) VALUES(EMP_SEQ.NEXTVAL, '김민서', 1, '사원', 'M', '17-09-01', 2500000);
INSERT INTO EMPLOYEE_TBL(EMP_NO,NAME, DEPART, POSITION, GENDER, HIRE_DATE, SALARY) VALUES(EMP_SEQ.NEXTVAL, '이은영', 2, '부장', 'F', '90-09-01', 5500000);
INSERT INTO EMPLOYEE_TBL(EMP_NO,NAME, DEPART, POSITION, GENDER, HIRE_DATE, SALARY) VALUES(EMP_SEQ.NEXTVAL, '한성일', 2, '과장', 'M', '93-04-01', 5000000);





